maven-wrapper-plugin/src/main/java/org/apache/maven/plugins/wrapper/WrapperMojo.java
The license added to the wrapper properties file uses a template with a hardcoded "\n" line separator, and later the properties are written with System.lineSeparator(), this can create a file with mixed line separator.
=> [MWRAPPER-40] Fix line separators in wrapper properties file

maven-wrapper-distribution/src/resources/mvn/wrapper/MavenWrapperDownloader.java, maven-wrapper-distribution/src/resources/mvnw
This adds `--quiet` to wget and `--silent` to curl by default, and only when MVNW_VERBOSE is set to true it prints the download information.
Also the MavenWrapperDownloader.java is modified to read and print based on MVNW_VERBOSE.
=> [MWRAPPER-43] Make jar download quiet by default

maven-wrapper-distribution/src/resources/mvnw, maven-wrapper-distribution/src/resources/mvnw.cmd
Replaced jarUrl with wrapperUrl in mvnw
My first maven contribution in 15 years or so. Please advise if I missed out on something.
=> [MWRAPPER-47] - Use name wrapperUrl consistently in Maven Wrapper files/scripts

.github/workflows/maven-verify.yml
From v2 for shared GitHub Action duplicate build on PR are skipped in script,
so we shouldn't ignore dependabot branches
=> Don't ignore dependabot branches for shared GH v2

maven-wrapper-plugin/src/site/markdown/usage.md
Adaptation of documentation to current behavior: https://github.com/apache/maven-wrapper/blob/master/maven-wrapper-plugin/src/main/java/org/apache/maven/plugins/wrapper/WrapperMojo.java#L98
=> (doc) Fixing doc about installing mvnDebug-scripts

maven-wrapper-distribution/src/resources/mvn/wrapper/MavenWrapperDownloader.java, maven-wrapper-distribution/src/resources/mvnw
This simplifies the MavenWrapperDownloader.java script by removing many of the redundant code that was already done on the shell script, fixing the problem when MVNW_REPOURL env variable was used but not read by the MavenWrapperDownloader.java.
Also wrap the calls when MVNW_VERBOSE is used to a log function in the shell script.
commit …
=> [MWRAPPER-65] MavenWrapperDownloader.java ignores the MVNW_REPOURL env

maven-wrapper-distribution/pom.xml, maven-wrapper-distribution/src/assembly/only-script.xml, maven-wrapper-distribution/src/resources/only-mvnw, maven-wrapper-distribution/src/resources/only-mvnw.cmd, maven-wrapper-distribution/src/resources/only-mvnwDebug, maven-wrapper-distribution/src/resources/only-mvnwDebug.cmd, maven-wrapper-distribution/src/site/apt/index.apt.vm, maven-wrapper-plugin/src/it/projects/type_only-script/pom.xml, maven-wrapper-plugin/src/it/projects/type_only-script/test.properties, maven-wrapper-plugin/src/it/projects/type_only-script/verify.groovy
=> [MWRAPPER-61] Try to skip maven-wrapper.jar, call mvn directly from mvnw.

maven-wrapper-plugin/pom.xml
TODO test: Install the latest snapshot and try to update itself (see Hervé's comment in the JIRA issue).
----
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are …
=> [MWRAPPER-77] update to plexus archiver 4.6.0

src/site/xdoc/download.xml.vm
`project.artifactId` resolves to the project parent, but the source zip is named `maven-wrapper-${project.version}`
This fix hardcodes the name in download.xml.vm …
=> Corrected download links in generated site

maven-wrapper-distribution/src/resources/mvnw
Addresses a similar issue (not the same, but similar) as #44.
If Git checks out the jvm.config file with CRLF line endings, a condition can arise in Git Bash where \r does not get removed, resulting in -Xarg becoming $'-Xarg\r' and breaking builds on Windows. This is reproducible in environments like GitHub Actions runners.
I was using a GitHub Actions runner on windows-2022, using a manual step with the "bash" shell. This job was in a matrix running the same command and step on ubuntu-2022 and macos-12 runners.
The repository used the default CRLF settings provided by Git, and the issue was produced by this jvm.config:
```
-XX:+TieredCompilation -XX:TieredStopAtLevel=1
```
Builds on MacOS and Linux were fine.
On the Windows runner, I came across this when invoking mvnw:
```console
$ …
```
=> [MWRAPPER-95] Fix bug in mvnw to handle \r in jvm.config correctly

maven-wrapper-distribution/src/resources/mvnw
Usage of git bash will not download the maven wrapper jar along with curl (probably others) due to having windows line endings in the URL (trailing).  To ensure that is not the case, make sure to strip invalid line endings out before usage.
Use case, ./mvnw in powershell will use mvnw.cmd and has no issues downloading.  If user does same in git bash, it will fail with invalid URL error with curl.  Using ./mvnw.cmd there will work but not natural usage.  To ensure this simply just works for full support, trim out invalid line feeds.
note: This only affected the download.  It worked otherwise.
- [ x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MWRAPPER) filed 
for the change …
=> [MWRAPPER-67] Remove '\r' when using IFS on windows for wrapperUrl from mvnw script usage such as git bash

maven-wrapper-plugin/src/it/projects/type_only-script/verify.groovy, maven-wrapper-plugin/src/it/projects/type_script/verify.groovy, maven-wrapper-plugin/src/main/java/org/apache/maven/plugins/wrapper/WrapperMojo.java
When using the `only-script` distribution type, the `wrapperUrl` is not needed, will not be added to `maven-wrapper.properties` …
=> [MWRAPPER-120] -  Wrapper Plugin no longer add wrapperUrl property

maven-wrapper-distribution/src/resources/mvnw, maven-wrapper-distribution/src/resources/only-mvnw, pom.xml
This is an alternate proposal for running a bash linter. This time it integrates with spotless (and you can use spotlesss:apply). The other approach is using shellcheckk (https://github.com/apache/maven-wrapper/pull/82) which is a little more known and does not require npm modules, but does not integrate with spotless as nicely.
Signed-off-by: Benjamin Marwell <bmarwell@apache.org>
Fixes MWRAPPER-104
---
is to use the JIRA …
=> [MWRAPPER-104] add prettier config for shell

maven-wrapper-distribution/src/resources/only-mvnw
AIX's ksh's `printf %d` implementation cannot handle full string input.
Thus, create the hash char-by-char. This is what the implementation would have done anyway.
--- …
=> [MWRAPPER-123]  hash string char-by-char for AIX's ksh implementation

maven-wrapper-distribution/src/resources/mvnw
On a standard Ubuntu 20.04 Java installation (openjdk-17-jdk APT package, /usr/bin/javac linked to /usr/lib/jvm/java-17-openjdk-amd64/bin/javac via the update-alternatives system, no JAVA_HOME set), Maven Wrapper 3.2.0 prints this warning on each invocation:
> Warning: JAVA_HOME environment variable is not set.
This is caused by excessive quoting that adds literal double quotes to the resolution of javaHome and javaExecutable. (Some nearby invocations of "expr" use correct quoting, but several are wrong. There might have been obscure bugs and someone thought that more quoting is better. That code has been in the codebase since the beginning, taken over from the gradlew wrapper (which had the shell wrappers completely rewritten; there are no remnants of this code found there any longer).) …
=> [MWRAPPER-112] Detection of JAVA_HOME fails due to bad quoting

maven-wrapper-distribution/src/resources/mvnw, maven-wrapper-distribution/src/resources/mvnw.cmd
Errors and warnings from the wrapper should go to standard error, so that those are also shown to the user when the regular Maven output is suppressed, redirected into a file, or captured by a script.
For the latter use case, separation is especially critical because otherwise error output is mistakenly interpreted as desired Maven output (for example, when obtaining the list of Maven project names in the reactor with `mvnw --quiet -Dexec.executable=echo '-Dexec.args=${project.groupId}:${project.artifactId}' org.codehaus.mojo:exec-maven-plugin:exec`).
The current wrapper scripts do this only inconsistently, and so warnings like `Warning: JAVA_HOME environment variable is not set.` are printed to _stdout_ instead of _stderr_.
Following this checklist to help us incorporate your …
=> [MWRAPPER-113] Some mvnw error and warning output goes to standard output

maven-wrapper-plugin/pom.xml, maven-wrapper-plugin/src/main/java/org/apache/maven/plugins/wrapper/WrapperMojo.java, maven-wrapper-plugin/src/test/java/org/apache/maven/plugins/wrapper/WrapperMojoTest.java
* first commit tries to fixes the problem, except I actually used `- 2` instead of  `- 1`
* Refactored the methods a bit to make them easier to test
* Added a few tests for the most common cases
* Opened a field and method for testing to `protected`
* Don't use too short repo URLs where not even the protocol could fit.
---
be …
=> [MWRAPPER-86] Trim repourl and other checks; tests

maven-wrapper-plugin/pom.xml, maven-wrapper/pom.xml, pom.xml
Also refresh and reshuffle to not duplicate dependencies and versions. Tend to use properties for versions where there is 2+ of them, otherwise is just fluff.
---
https://issues.apache.org/jira/browse/MWRAPPER-128
https://issues.apache.org/jira/browse/MWRAPPER-129
=> [MWRAPPER-129][MWRAPPER-128] Drop legacy stuff, require Maven 3.6.3+

maven-wrapper-distribution/src/resources/only-mvnw, maven-wrapper-plugin/src/it/projects/type_only-script-fail/invoker.properties, maven-wrapper-plugin/src/it/projects/type_only-script-fail/pom.xml, maven-wrapper-plugin/src/it/projects/type_only-script-fail/test.properties, maven-wrapper-plugin/src/it/projects/type_only-script-fail/verify.groovy
Script silently just failed. Reused changes from dead PR https://github.com/apache/maven-wrapper/pull/98 w/ help of @michael-o :+1:  Thanks both!
---
https://issues.apache.org/jira/browse/MWRAPPER-108
=> [MWRAPPER-108] Emit clear error message when download fails on U*IX

maven-wrapper-distribution/src/resources/mvn/wrapper/MavenWrapperDownloader.java, maven-wrapper/src/main/java/org/apache/maven/wrapper/DefaultDownloader.java
Stream into temp file in same dir, and at the end move the stuff into file place.
---
https://issues.apache.org/jira/browse/MWRAPPER-131
=> [MWRAPPER-131] Make downloader not stream into final target file

maven-wrapper-distribution/src/resources/only-mvnw
port pr https://github.com/apache/maven-wrapper/pull/120
Test Method:
```bash
sed -n '/public class Downloader/,/\t}/p' maven-wrapper-distribution/src/resources/only-mvnw > Downloader.java
jenv shell 21 ## or 1.7, 1.8, 11, 17
javac -version
javac Downloader.java -Xlint:all -Werror
```
Passed lint compile test with jdk 1.7, 1.8, 11, 17 and 21
---
https://issues.apache.org/jira/browse/MWRAPPER-132
=> [MWRAPPER-132][MWRAPPER-124] port MWRAPPER-124 fix to only-script

maven-wrapper-plugin/src/it/projects/default/verify.groovy, maven-wrapper-plugin/src/it/projects/mavenversion/verify.groovy, maven-wrapper-plugin/src/it/projects/type_bin/verify.groovy, maven-wrapper-plugin/src/it/projects/type_only-script/verify.groovy, maven-wrapper-plugin/src/it/projects/type_script/verify.groovy, maven-wrapper-plugin/src/it/projects/type_source/verify.groovy, maven-wrapper-plugin/src/main/java/org/apache/maven/plugins/wrapper/WrapperMojo.java
Adds `distributionType` to `maven-wrapper.properties`.
https://issues.apache.org/jira/browse/MWRAPPER-135
=> [MWRAPPER-135] Provide a reliable way to determine the Maven Wrapper type

maven-wrapper-plugin/src/it/projects/upgrade_with_existing_type/.mvn/wrapper/maven-wrapper.properties, maven-wrapper-plugin/src/it/projects/upgrade_with_existing_type/invoker.properties, maven-wrapper-plugin/src/it/projects/upgrade_with_existing_type/pom.xml, maven-wrapper-plugin/src/it/projects/upgrade_with_existing_type/verify.groovy, maven-wrapper-plugin/src/main/java/org/apache/maven/plugins/wrapper/WrapperMojo.java, maven-wrapper-plugin/src/site/markdown/usage.md
Uses `distributionType` from `.mvn/wrapper/maven-wrapper.properties` by default, when present.
https://issues.apache.org/jira/browse/MWRAPPER-141
=> [MWRAPPER-141] Use distribution type of existing Maven Wrapper by default

maven-wrapper-distribution/src/resources/only-mvnw
MWRAPPER-139: Remove trailing whitespace from fields in maven-wrapper.properties
This prevents issues due to confusion between CRLF and LF when running in more exotic locations such as MINGW on Windows but using ./mvnw rather than ./mvnw.cmd. A prime example of where this is an issue would be on windows-latest GitHub Actions runners.
Fixes MWRAPPER-139, MWRAPPER-137 (which I didn't spot for some reason when reviewing the
existing tickets on JIRA... might have been a blip in JIRA that didn't display it?).
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
=> MWRAPPER-139: Remove trailing whitespace from fields in properties

maven-wrapper-distribution/src/resources/only-mvnw, maven-wrapper-distribution/src/resources/only-mvnw.cmd
User provided patch to "only-script" type (as bin does support it).
---
https://issues.apache.org/jira/browse/MWRAPPER-140
=> [MWRAPPER-140] only-script type does not honor MAVEN_USER_HOME

maven-wrapper-distribution/src/resources/mvnw
JIRA issue: https://issues.apache.org/jira/projects/MWRAPPER/issues/MWRAPPER-111
This PR trims the values read from the property files by removing whitespace such as newlines.
This has already be done in the case of `maven-wrapper-distribution/src/resources/only-mvnw`, but it's missing from `maven-wrapper-distribution/src/resources/mvnw`.
With this change, validating the wrapper checksum no longer fails if the property file has CLRF line endings.
=> [MWRAPPER-111] Trim whitespace when reading from properties file

maven-wrapper-distribution/src/resources/mvnw, maven-wrapper-distribution/src/resources/only-mvnw
The version of `sha256sum` that ships with macOS Sequoia appears to have a bug where it does not read from stdin by default, even though its `man` page says, in part (emphasis added):
> In all cases, each file listed on the command line is processed separately.  **If no files are listed on the command line**, or a file name is given as -, input is taken from stdin instead.
…but invoking `sha256` as it appears in the `mvnw` script does not work as expected:
```sh
❯ echo '3d8f20ce6103913be8b52aef6d994e0c54705fb527324ceb9b835b338739c7a8  /Users/jon/REDACTED/.mvn/wrapper/maven-wrapper.jar' | sha256sum -c
usage: sha256sum [-bctwz] [files ...]
```
…which in turn results in a non-successful exit code, which in turn leads to a (rather alarming!) warning about a mismatched checksums and possible …
=> [MWRAPPER-150] - Fails to validate checksums on MacOS Sequoia

maven-wrapper-distribution/src/resources/only-mvnw.cmd
Following this checklist to help us incorporate your contribution quickly and easily:
- [ X Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
please ask on …
=> [MWRAPPER-147] mvnw.cmd fails to launch maven if username contains space

.asf.yaml, README.md, pom.xml, src/site/site.xml
see https://github.com/apache/maven-site/pull/838
=> site is now /tools/wrapper

src/site/markdown/index.md
=> Copy edit docs

maven-wrapper-plugin/src/it/projects/default/verify.groovy, maven-wrapper-plugin/src/it/projects/mavenversion/verify.groovy, maven-wrapper-plugin/src/it/projects/sh_type_only-script/verify.groovy, maven-wrapper-plugin/src/it/projects/type_only-script/verify.groovy, maven-wrapper-plugin/src/main/java/org/apache/maven/plugins/wrapper/WrapperMojo.java
The only-script mode doesn't use the wrapper distribution, this property is now only added to the maven-wrapper.properties file when other types are used. …
=> [MWRAPPER-143] - The wrapperVersion property is not used in only-script mode
